# Generated by Django 5.0.7 on 2025-12-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_cameraconfiguration_success_sound_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomObjectDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_detected', models.DateTimeField(auto_now_add=True)),
                ('object_type', models.CharField(choices=[('mobile_phone', 'Mobile Phone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('smartwatch', 'Smartwatch'), ('headphones', 'Headphones'), ('camera', 'Camera'), ('other_gadget', 'Other Electronic Gadget')], max_length=50)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Detection confidence (0-1)')),
                ('location_x', models.IntegerField(blank=True, help_text='X coordinate of detected object', null=True)),
                ('location_y', models.IntegerField(blank=True, help_text='Y coordinate of detected object', null=True)),
                ('width', models.IntegerField(blank=True, help_text='Object bounding box width', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Object bounding box height', null=True)),
                ('image_snapshot', models.ImageField(blank=True, help_text='Snapshot of detected object', null=True, upload_to='detections/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the detection')),
                ('camera_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.cameraconfiguration')),
            ],
            options={
                'ordering': ['-date_detected'],
            },
        ),
    ]
