# Generated by Django 5.0.7 on 2025-12-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_classroomobjectdetection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-check_in_time']},
        ),
    ]
